
services:
    postgres_db_nix:
        container_name: db_nix
        image: postgres:11
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user_db
            POSTGRES_PASSWORD: xEhs5hU26nDNdeC
            POSTGRES_DB: nix_db
            PGDATA: ./database/data:/var/lib/postgresql/data
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"

volumes:
  postgres: