services:
    postgres_db:
        container_name: db_nix
        image: postgres:11
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user_db
            POSTGRES_PASSWORD: xEhs5hU26nDNdeC
            POSTGRES_DB: nix_db
        volumes:
            - ./postgres/database:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"

    flask:
        # docker container exec -it flask_app /bin/bash     
        # open container -> create to migrate and add data
        container_name: flask_app
        build: ./app
        # command: gunicorn --bind 0.0.0.0:5000 run:app
        command: python run.py
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - postgres_db
        volumes:
            - ./app:/home/app

    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - flask

