"""fix -9

Revision ID: 12033bf1ee4c
Revises: afe7c81dfb79
Create Date: 2023-03-30 19:00:31.277384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12033bf1ee4c'
down_revision = 'afe7c81dfb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'path')
    op.drop_column('storage', 'type')
    op.drop_column('storage', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('storage', sa.Column('type', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('storage', sa.Column('path', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
