"""empty message

Revision ID: 208dd1a6bd93
Revises: 463869d2f84c
Create Date: 2023-04-28 11:43:56.891056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208dd1a6bd93'
down_revision = '463869d2f84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
