"""empty message

Revision ID: 463869d2f84c
Revises: acd0a36fc2ce
Create Date: 2023-04-26 20:39:53.313002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463869d2f84c'
down_revision = 'acd0a36fc2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    # ### end Alembic commands ###
