"""fix -30

Revision ID: 6ed90d89392f
Revises: fc7b86e058eb
Create Date: 2023-04-05 19:31:19.790221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed90d89392f'
down_revision = 'fc7b86e058eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reliase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reliase_year'), 'reliase', ['year'], unique=True)
    op.add_column('movies', sa.Column('reliases', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('reliase_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movies', 'reliase', ['reliase_id'], ['id'])
    op.drop_column('movies', 'reliase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('reliase', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'reliase_id')
    op.drop_column('movies', 'reliases')
    op.drop_index(op.f('ix_reliase_year'), table_name='reliase')
    op.drop_table('reliase')
    # ### end Alembic commands ###
