"""empty message

Revision ID: 78f3d4cfbad1
Revises: ce325b5fa514
Create Date: 2023-04-22 13:09:52.931563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f3d4cfbad1'
down_revision = 'ce325b5fa514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create')
    # ### end Alembic commands ###
