"""fix -13

Revision ID: 80b22c2ebdf4
Revises: 926abd468be4
Create Date: 2023-03-31 16:26:39.894704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b22c2ebdf4'
down_revision = '926abd468be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
