"""fix -23

Revision ID: 88cf5c4fab39
Revises: 8e902f1d648a
Create Date: 2023-04-02 19:25:32.889711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cf5c4fab39'
down_revision = '8e902f1d648a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_director_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'directors', ['director_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_director_id_fkey', 'movies', 'directors', ['director_id'], ['id'])
    # ### end Alembic commands ###
