"""fix -14

Revision ID: 8e902f1d648a
Revises: 80b22c2ebdf4
Create Date: 2023-03-31 20:21:14.173097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e902f1d648a'
down_revision = '80b22c2ebdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_director_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'directors', ['director_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_director_id_fkey', 'movies', 'directors', ['director_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
