"""fix -12

Revision ID: 926abd468be4
Revises: 4056d6652103
Create Date: 2023-03-31 16:25:28.519531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926abd468be4'
down_revision = '4056d6652103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('movies_director_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'directors', ['director_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_director_id_fkey', 'movies', 'directors', ['director_id'], ['id'])
    op.alter_column('movies', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
