"""empty message

Revision ID: b092c07c3165
Revises: 1d0b6b243786
Create Date: 2023-04-20 00:49:17.063121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b092c07c3165'
down_revision = '1d0b6b243786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwd', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwd')
    # ### end Alembic commands ###
