"""empty message

Revision ID: ce325b5fa514
Revises: 372a29d6d0d4
Create Date: 2023-04-22 13:08:09.910324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce325b5fa514'
down_revision = '372a29d6d0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
