"""fix -6

Revision ID: e32af5d6ab0b
Revises: 4225d157751b
Create Date: 2023-03-30 13:06:35.978214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32af5d6ab0b'
down_revision = '4225d157751b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_movie')
    op.add_column('movies', sa.Column('genres_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movies', 'genres', ['genres_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'genres_id')
    op.create_table('genre_movie',
    sa.Column('movies_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genres_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genres_id'], ['genres.id'], name='genre_movie_genres_id_fkey'),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], name='genre_movie_movies_id_fkey')
    )
    # ### end Alembic commands ###
