"""fix -25

Revision ID: e3830eb7aa2a
Revises: 88cf5c4fab39
Create Date: 2023-04-03 12:01:12.433289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3830eb7aa2a'
down_revision = '88cf5c4fab39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_rating_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'ratings', ['rating_id'], ['star'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_rating_id_fkey', 'movies', 'ratings', ['rating_id'], ['id'])
    # ### end Alembic commands ###
